### ISSUE TITLE
Constantly fails - Internal Server Error

### ISSUE THREAD

**Issue by engardeknave** [hartez/PneumaticTube#18]
Is this just dropbox?  I never have this problem uploading manually via a browser.

Uploading 11909.zip to /
Ctrl-C to cancel
An error occurred and your file was not uploaded.
InternalServerError
StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  pragma: no-cache
  X-Dropbox-Request-Id: 4fe1114e7d1b4027d7d64de565c96170
  X-Robots-Tag: noindex, nofollow, noimageindex
  Cache-Control: no-cache
  Date: Wed, 02 Mar 2016 04:50:43 GMT
  Server: nginx
  Content-Type: text/html; charset=utf-8
}

**Comment by chipbite** [comment]
@engardeknave : Did you figure this out? (I use it daily and it works in my context)

**Comment by engardeknave** [comment]
Yeah, at some point it seems to have stopped doing that.
