### ISSUE TITLE
Dropbox API v1 being deprecated

### ISSUE THREAD

**Issue by mohitcv** [hartez/PneumaticTube#19]
Hi,

I received an e-mail from Dropbox saying that API v1 will be deprecated on June 28, 2017.

Do you have plans to use a library that supports the API v2?

Thanks!

**Comment by digitaltoast** [comment]
👍 Same

**Comment by chipbite** [comment]
gah! nooo! :-)

**Comment by hartez** [comment]
The [latest release](https://github.com/hartez/PneumaticTube/releases/tag/v1.3) supports API v2.

**Comment by hartez** [comment]
(Also, I'm working on getting the chocolatey package updated if that's how you usually do your installs.)
