### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by david-navigator** [hartez/PneumaticTube#24]
Getting the error An error occurred and your file was not uploaded.
followed by the string path/conflict/file/.

Any clue as to what might or might not be happening and how to debug ?

David

===============================================
 pneumatictube -f "C:\ProgramData\backups\Thursday\Active.zip" -p "/Everyone/Cloud_backups/Active/Thursday/Active"
Uploading Active.zip to /Everyone/Cloud_backups/Active/Thursday/Active
Ctrl-C to cancel
File is larger than 150MB, using chunked uploading.
99% complete.An error occurred and your file was not uploaded.
path/conflict/file/.

**Comment by derekantrican** [comment]
I ran into this too. It seems that PneumaticTube does not use the "Overwrite" option when doing chunked uploading. I'm working on it now
