### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by Ealendir** [hartez/PneumaticTube#6]
How to specify the Dropbox path ? I always get this error: System.NullReferenceException: PneumaticTube.Program.Main(String[] args)

**Comment by hartez** [comment]
@Ealendir - the Dropbox path is specified with the `-p` option. 

You can specify it from the Dropbox root:
`pneumatictube -f .\report.txt -p /docs`

The leading `/` is optional; it always starts from the root. So
`pneumatictube -f .\report.txt -p docs2/docs3`
will create a `docs2` folder at the Dropbox root (if one doesn't already exist), then create `docs3` within `docs2`, and `report.txt` will be in `docs3'.

Can you give me an example of a path that's giving you the NullReferenceException?

**Comment by Ealendir** [comment]
its this command:

C:\Users\Administrator>pneumatictube -f "C:\tmp\Direwolf20Server.zip" -p Minecraft/ServerBackups
Uploading Direwolf20Server.zip to minecraft/ServerBackups

System.NullReferenceException: Object reference not set to an instance to an object
   at PneumaticTube.Program.Main(String[] args)

it always seems to work until the upload ends, then the message comes up.....

**Comment by hartez** [comment]
How large is the file you're trying to send? And does it take a little
while before the error pops up, or does it happen right away?

**Comment by hartez** [comment]
Now supports chunked uploading (for files over 150 MB) and better error messages.
