### ISSUE TITLE
Missing apikeys.txt

### ISSUE THREAD

**Issue by WilliamAtSamraksh** [hartez/PneumaticTube#7]
The command line program works great; thanks. The source solution is missing apikeys.txt. While the format of the file is clear from the code, it's not clear what I need to provide. Any pointer?

tia, Bill

**Comment by hartez** [comment]
The apikeys.txt file is deliberately missing; it contains the secret API keys for PneumaticTube. 

If you're looking to build your own app from source, you'll need to go to https://www.dropbox.com/developers/apps and create your own DropBox app. Once you've done that, you'll be given an API key and an API secret for your app. 

Add the missing 'apikeys.txt' file to the project and set the Build Action to 'Embedded Resource'. Your app's API key goes on the first line, and the API secret goes on the second line.
